In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\elise\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\elise\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elise\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\elise\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elise\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\elise\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("sales.xlsx")

In [5]:
# head() - it shows first five rows from data
# tail() - it shows last five rows from data

In [6]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi

In [7]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh
14,1015,2025-01-09,C114,Ajay,Mumbai,Headphones,Electronics,3,2700,300,Card,Ravi

In [8]:
# how many records are there in data?
# which columns are available?
# Are there any missing values?

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       15 non-null     int64
 1   OrderDate     15 non-null     datetime64[ns]
 2   CustomerID    15 non-null     object
 3   CustomerName  15 non-null     object
 4   City          15 non-null     object
 5   Product       15 non-null     object
 6   Category      15 non-null     object
 7   Quantity      15 non-null     int64
 8   Price         15 non-null     int64
 9   Discount      15 non-null     int64
 10  PaymentMode   15 non-null     object
 11  SalesPerson   15 non-null     object
dtypes: datetime64[ns](1), int64(4), object(7)
memory usage: 1.5+ KB

In [10]:
df.shape

(15, 12)

In [11]:
df["CustomerName"]

0      Rahul
1      Priya
2      Arjun
3      Rahul
4      Sneha
5       Teja
6        Ram
7     Anjali
8      Mohan
9      Kavya
10    Rakesh
11     Divya
12     Varun
13     Pooja
14      Ajay
Name: CustomerName, dtype: object

In [12]:
df[["CustomerName", "City"]]

   CustomerName       City
0         Rahul  Hyderabad
1         Priya    Chennai
2         Arjun  Bangalore
3         Rahul  Hyderabad
4         Sneha     Mumbai
5          Teja  Hyderabad
6           Ram    Chennai
7        Anjali  Bangalore
8         Mohan  Hyderabad
9         Kavya     Mumbai
10       Rakesh    Chennai
11        Divya  Bangalore
12        Varun  Hyderabad
13        Pooja    Chennai
14         Ajay     Mumbai

In [13]:
# data filtering

In [14]:
df[df["Product"] == "Mobile"]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran

In [15]:
df["Product"] == "Mobile"

0     False
1      True
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
Name: Product, dtype: bool

In [16]:
df[(df["City"] == "Hyderabad") & (df["Price"] > 20000)]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi

In [17]:
df[(df["City"] == "Hyderabad") | (df["Price"] > 20000)]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi
9,1010,2025-01-06,C109,Kavya,Mumbai,Laptop,Electronics,1,60000,3000,Card,Suresh
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh

In [18]:
df.head(3)

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi

In [19]:
# revenue = quantity * price - discount

In [20]:
df["Revenue"] = (df["Quantity"] * df["Price"]) - df["Discount"]

In [21]:
df.head(2)

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000

In [22]:
# sort_values

In [23]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000

In [25]:
df.sort_values(by = "Price", ascending = True)

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100
7,1008,2025-01-05,C107,Anjali,Bangalore,Headphones,Electronics,2,2500,200,Card,Kiran,4800
14,1015,2025-01-09,C114,Ajay,Mumbai,Headphones,Electronics,3,2700,300,Card,Ravi,7800
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi,13600
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi,6500
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi,8700
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran,21000
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi,23500
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh,49500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
9,1010,2025-01-06,C109,Kavya,Mumbai,Laptop,Electronics,1,60000,3000,Card,Suresh,57000

In [26]:
df.sort_values(by = "Price", ascending = False)

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
9,1010,2025-01-06,C109,Kavya,Mumbai,Laptop,Electronics,1,60000,3000,Card,Suresh,57000
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh,49500
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi,23500
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran,21000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi,8700
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi,6500
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi,13600
14,1015,2025-01-09,C114,Ajay,Mumbai,Headphones,Electronics,3,2700,300,Card,Ravi,7800
7,1008,2025-01-05,C107,Anjali,Bangalore,Headphones,Electronics,2,2500,200,Card,Kiran,4800
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100

In [27]:
#unique()

In [28]:
df["City"].unique()

array(['Hyderabad', 'Chennai', 'Bangalore', 'Mumbai'], dtype=object)

In [29]:
#nunique()

In [30]:
df["City"].nunique()

4

In [31]:
#value_counts()

In [32]:
df["City"].value_counts()

City
Hyderabad    5
Chennai      4
Bangalore    3
Mumbai       3
Name: count, dtype: int64

In [33]:
#isnull()

In [35]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerID      0
CustomerName    0
City            0
Product         0
Category        0
Quantity        0
Price           0
Discount        0
PaymentMode     0
SalesPerson     0
Revenue         0
dtype: int64

In [36]:
#notnull()

In [38]:
df.notnull().sum()

OrderID         15
OrderDate       15
CustomerID      15
CustomerName    15
City            15
Product         15
Category        15
Quantity        15
Price           15
Discount        15
PaymentMode     15
SalesPerson     15
Revenue         15
dtype: int64

In [39]:
# fillna()

In [40]:
df["City"] = df["City"].fillna("Unknown")

In [41]:
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [42]:
# dropna()

In [45]:
df.dropna(axis = 0)

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi,23500
7,1008,2025-01-05,C107,Anjali,Bangalore,Headphones,Electronics,2,2500,200,Card,Kiran,4800
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi,6500
9,1010,2025-01-06,C109,Kavya,Mumbai,Laptop,Electronics,1,60000,3000,Card,Suresh,57000
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi,8700
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran,21000
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi,13600
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh,49500
14,1015,2025-01-09,C114,Ajay,Mumbai,Headphones,Electronics,3,2700,300,Card,Ravi,7800

In [46]:
# duplicated()

In [47]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [48]:
# drop_duplicates()

In [49]:
df.drop_duplicates()

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100
6,1007,2025-01-04,C106,Ram,Chennai,Mobile,Electronics,1,25000,1500,UPI,Ravi,23500
7,1008,2025-01-05,C107,Anjali,Bangalore,Headphones,Electronics,2,2500,200,Card,Kiran,4800
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi,6500
9,1010,2025-01-06,C109,Kavya,Mumbai,Laptop,Electronics,1,60000,3000,Card,Suresh,57000
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi,8700
11,1012,2025-01-07,C111,Divya,Bangalore,Mobile,Electronics,1,22000,1000,Card,Kiran,21000
12,1013,2025-01-08,C112,Varun,Hyderabad,Shoes,Fashion,5,2800,400,Cash,Ravi,13600
13,1014,2025-01-08,C113,Pooja,Chennai,Laptop,Electronics,1,52000,2500,UPI,Suresh,49500
14,1015,2025-01-09,C114,Ajay,Mumbai,Headphones,Electronics,3,2700,300,Card,Ravi,7800

In [50]:
# string functions

In [51]:
# upper()

In [53]:
df["CustomerName"].str.upper()

0      RAHUL
1      PRIYA
2      ARJUN
3      RAHUL
4      SNEHA
5       TEJA
6        RAM
7     ANJALI
8      MOHAN
9      KAVYA
10    RAKESH
11     DIVYA
12     VARUN
13     POOJA
14      AJAY
Name: CustomerName, dtype: object

In [55]:
# lower()

In [56]:
# gnanesh elisetty
# title()

In [57]:
# Gnanesh Elisetty

In [58]:
# len()

In [59]:
df["CustomerName"].str.len()

0     5
1     5
2     5
3     5
4     5
5     4
6     3
7     6
8     5
9     5
10    6
11    5
12    5
13    5
14    4
Name: CustomerName, dtype: int64

In [60]:
# contains()

In [63]:
df[df["CustomerName"].str.contains("h")]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
8,1009,2025-01-05,C108,Mohan,Hyderabad,Shoes,Fashion,2,3500,500,Cash,Ravi,6500
10,1011,2025-01-06,C110,Rakesh,Chennai,Watch,Accessories,2,4500,300,UPI,Ravi,8700

In [64]:
# replace()

In [65]:
df["Product"].str.replace("Laptop", "Dell Laptop")

0     Dell Laptop
1          Mobile
2           Shoes
3           Watch
4     Dell Laptop
5          TShirt
6          Mobile
7      Headphones
8           Shoes
9     Dell Laptop
10          Watch
11         Mobile
12          Shoes
13    Dell Laptop
14     Headphones
Name: Product, dtype: object

In [66]:
# loc[] and iloc[]

In [67]:
# loc[]

In [68]:
df.loc[[0, 5]]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100

In [69]:
df.loc[0 : 5]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
1,1002,2025-01-02,C102,Priya,Chennai,Mobile,Electronics,2,20000,1000,Card,Suresh,39000
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
3,1004,2025-01-03,C101,Rahul,Hyderabad,Watch,Accessories,1,5000,500,UPI,Kiran,4500
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000
5,1006,2025-01-04,C105,Teja,Hyderabad,TShirt,Fashion,4,800,100,Cash,Suresh,3100

In [71]:
df.loc[3, "CustomerName"]

'Rahul'

In [72]:
#iloc[]

In [73]:
df.iloc[[0, 2, 4]]

,OrderID,OrderDate,CustomerID,CustomerName,City,Product,Category,Quantity,Price,Discount,PaymentMode,SalesPerson,Revenue
0,1001,2025-01-01,C101,Rahul,Hyderabad,Laptop,Electronics,1,50000,5000,UPI,Ravi,45000
2,1003,2025-01-02,C103,Arjun,Bangalore,Shoes,Fashion,3,3000,300,Cash,Ravi,8700
4,1005,2025-01-03,C104,Sneha,Mumbai,Laptop,Electronics,1,55000,2000,Card,Ravi,53000

In [74]:
df.iloc[2:4, 2:4]

  CustomerID CustomerName
2       C103        Arjun
3       C101        Rahul

In [75]:
# groupby()

In [76]:
df["Revenue"].sum()

np.int64(345700)

In [77]:
df.groupby("City")["Revenue"].sum()

City
Bangalore     34500
Chennai      120700
Hyderabad     72700
Mumbai       117800
Name: Revenue, dtype: int64

In [80]:
df.groupby(["City", "Product"])["Revenue"].sum()

City       Product
Bangalore  Headphones      4800
           Mobile         21000
           Shoes           8700
Chennai    Laptop         49500
           Mobile         62500
           Watch           8700
Hyderabad  Laptop         45000
           Shoes          20100
           TShirt          3100
           Watch           4500
Mumbai     Headphones      7800
           Laptop        110000
Name: Revenue, dtype: int64

In [79]:
# aggregation -- agg()

In [81]:
df.groupby("City")["Revenue"].agg(["sum", "min", "max", "mean"])

              sum   min    max          mean
City
Bangalore   34500  4800  21000  11500.000000
Chennai    120700  8700  49500  30175.000000
Hyderabad   72700  3100  45000  14540.000000
Mumbai     117800  7800  57000  39266.666667

In [82]:
# pivot_table()

In [83]:
pd.pivot_table(df, values = "Revenue", index = "City", aggfunc = "sum")

           Revenue
City
Bangalore    34500
Chennai     120700
Hyderabad    72700
Mumbai      117800